name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B build -G Xcode \
            -DCMAKE_TOOLCHAIN_FILE=cmake/ios.cmake \
            -DIOS_PLATFORM=SIMULATOR
          cmake --build build --config Release

      - name: Install
        run: |
          xcrun simctl boot "iPhone 15"
          xcrun simctl install booted build/src/Release-iphonesimulator/MyApp.app
          xcrun simctl launch booted com.liumeo.my-app

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
