name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        generator: [Ninja, Xcode]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build with Ninja
        if: ${{ matrix.generator == 'Ninja' }}
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DPLATFORM=SIMULATORARM64
          cmake --build build
          cmake --install build

      - name: Build with Xcode
        if: ${{ matrix.generator == 'Xcode' }}
        run: |
          cmake -B build -G Xcode \
            -DPLATFORM=SIMULATORARM64
          cmake --build build --config Release

      - name: Install
        run: |
          xcrun simctl boot "iPhone 17"
          if [[ ${{ matrix.generator }} == "Ninja" ]]; then
            xcrun simctl install booted build/src/MyApp.app
          else
            xcrun simctl install booted build/src/Release-iphonesimulator/MyApp.app
          fi
          xcrun simctl launch booted com.liumeo.my-app

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
